### ISSUE TITLE
Dijkstra is missing when pip installing

### ISSUE THREAD

**Issue by Jaykingamez** [hasnainroopawalla/Ant-Colony-Optimization#11]
In the [example.py](https://github.com/hasnainroopawalla/Ant-Colony-Optimization/blob/00cd068597ab9a69a8eb81c8a3fd984797d2eefd/example.py), it links to a code which can't be used. For example, the Dijkstra

**Comment by hasnainroopawalla** [comment]
Hey @Jaykingamez, the `example.py` linked in the README was pointing to an older commit of the file. I've updated the link in PR #12.

Here is the link to the correct [example.py](https://github.com/hasnainroopawalla/ant-colony-optimization/blob/master/example.py) (from latest `master`) which uses Dijkstra from networkx.

Thanks for reporting this bug!
